# config.yaml
hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

# Data settings
dataset_name: "run_log"
seed: 0
windows: 6
train_percent: 0.1

# Model settings
model_name: "AE_skipLSTM_AR"
unit: 20
horizon: 4
highway: 6
skip_sizes: [3, 5, 7]

# Train options
epochs: 10

# Paths and miscellaneous settings
ensemble_space: 3

# Threshold settings
num_change_threshold: 7
num_ano_cpd: 3
threshold_high: 4
threshold_low: 1.4
epochs_to_train_after_cpd: 100
extra_samples_after_cpd: 3
epochs_to_train_single_sample: 5

# Learning rate and other model-specific settings
lr: 0.001
GRUUnits: ${unit}
SkipGRUUnits: ${unit}
